const { GAMES, PLAY_TYPES, generateRandomTicket, generatePersonalTicket, normalizeFavorites } = window.LotteryCore;

const gameEl=document.querySelector('#game'), modeEl=document.querySelector('#mode'), playTypeEl=document.querySelector('#play-type'), playTypeWrap=document.querySelector('#play-type-wrap'), countEl=document.querySelector('#ticket-count');
const preferencePanel=document.querySelector('#preference-panel'), mainFavoritesEl=document.querySelector('#main-favorites'), mainFavoritesLabel=document.querySelector('#main-favorites-label'), mainFavoritesHelp=document.querySelector('#main-favorites-help'), specialFavoritesWrap=document.querySelector('#special-favorites-wrap'), specialFavoritesEl=document.querySelector('#special-favorites'), specialFavoritesLabel=document.querySelector('#special-favorites-label'), specialFavoritesHelp=document.querySelector('#special-favorites-help'), preferenceStatus=document.querySelector('#preference-status');
const ticketsEl=document.querySelector('#tickets'), copyEl=document.querySelector('#copy'), statsGameEl=document.querySelector('#stats-game'), statsSessionEl=document.querySelector('#stats-session'), statsSessionWrap=document.querySelector('#stats-session-wrap'), statsCoverageEl=document.querySelector('#stats-coverage'), statsResultsEl=document.querySelector('#stats-results'), installCard=document.querySelector('#install-card'), installButton=document.querySelector('#install'), installHelp=document.querySelector('#install-help');
let currentTickets=[], deferredInstall; const lastPersonalTickets=new Map();

Object.entries(GAMES).forEach(([value,config])=>{const o=document.createElement('option');o.value=value;o.textContent=config.name;gameEl.append(o);const s=document.createElement('option');s.value=value;s.textContent=config.name;statsGameEl.append(s);});
if(document.querySelector('#stats-checked')) document.querySelector('#stats-checked').textContent=window.LotteryHistory?.checked||'';

function randomUnit(){const v=new Uint32Array(1);crypto.getRandomValues(v);return v[0]/4294967296;}
function parseFavoriteInput(input,min,max){const supplied=input.trim()?input.trim().split(/[^0-9]+/).filter(Boolean).map(Number):[];const valid=normalizeFavorites(supplied,min,max);return {valid,ignored:supplied.length-valid.length};}
function favoriteSummary(){const config=GAMES[gameEl.value];const main=parseFavoriteInput(mainFavoritesEl.value,config.min,config.max);const special=config.special?parseFavoriteInput(specialFavoritesEl.value,config.special.min,config.special.max):{valid:[],ignored:0};const parts=[main.valid.length?`Using ${main.valid.length} main favorite${main.valid.length===1?'':'s'}.`:'No main favorites entered; balanced variety will still be used.'];if(config.special)parts.push(special.valid.length?`Using ${special.valid.length} ${config.special.name} favorite${special.valid.length===1?'':'s'}.`:`No favorite ${config.special.name} entered.`);if(main.ignored+special.ignored>0)parts.push('Numbers outside the allowed range were ignored.');preferenceStatus.textContent=parts.join(' ');return {main:main.valid,special:special.valid};}
function updatePreferenceControls(){const config=GAMES[gameEl.value];const isDigits=config.repeats;preferencePanel.hidden=modeEl.value!=='personal';mainFavoritesLabel.textContent=isDigits?'Favorite digits':'Favorite main numbers';mainFavoritesEl.placeholder=isDigits?'Example: 1, 4, 7':`Example: ${config.min}, ${Math.ceil(config.max/2)}, ${config.max}`;mainFavoritesHelp.textContent=isDigits?'Enter any digits from 0 through 9, separated by spaces or commas.':`Enter any main numbers from ${config.min} through ${config.max}, separated by spaces or commas.`;specialFavoritesWrap.hidden=!config.special;if(config.special){specialFavoritesLabel.textContent=`Favorite ${config.special.name} numbers`;specialFavoritesEl.placeholder=`Example: ${config.special.min}, ${Math.ceil(config.special.max/2)}, ${config.special.max}`;specialFavoritesHelp.textContent=`Enter ${config.special.name} favorites from ${config.special.min} through ${config.special.max}.`;}favoriteSummary();}
function resetTickets(){currentTickets=[];ticketsEl.innerHTML='<p class="empty">Choose your settings, then generate tickets.</p>';copyEl.disabled=true;}
function updateGame(){const types=PLAY_TYPES[gameEl.value]||[];playTypeWrap.hidden=!types.length;playTypeEl.replaceChildren(...types.map(([value,label])=>{const o=document.createElement('option');o.value=value;o.textContent=label;return o;}));updatePreferenceControls();resetTickets();}
function renderTickets(){const config=GAMES[gameEl.value];ticketsEl.replaceChildren();currentTickets.forEach((ticket,index)=>{const row=document.createElement('div');row.className='ticket';const label=document.createElement('span');label.className='ticket-label';label.textContent=`${index+1}. ${ticket.playLabel||''}`;row.append(label);ticket.main.forEach(number=>{const ball=document.createElement('span');ball.className='ticket-number';ball.textContent=number;row.append(ball);});if(ticket.special!==null){const ball=document.createElement('span');ball.className='ticket-number special';ball.title=config.special.name;ball.textContent=ticket.special;row.append(ball);}ticketsEl.append(row);});copyEl.disabled=!currentTickets.length;}
function generateTickets(){const count=Number(countEl.value);if(modeEl.value==='random'){currentTickets=Array.from({length:count},()=>generateRandomTicket(gameEl.value,playTypeEl.value,randomUnit));}else{const favorites=favoriteSummary();currentTickets=[];for(let i=0;i<count;i++){const ticket=generatePersonalTicket(gameEl.value,playTypeEl.value,{mainFavorites:favorites.main,specialFavorites:favorites.special,previousTicket:lastPersonalTickets.get(gameEl.value)||null,random:randomUnit});currentTickets.push(ticket);lastPersonalTickets.set(gameEl.value,ticket);}}renderTickets();}
function statBox(title,content){const box=document.createElement('article');box.className='stat-box';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=content;box.append(h,p);return box;}
function renderStatistics(){const game=statsGameEl.value;const daily=game==='pick3'||game==='pick4';statsSessionWrap.hidden=!daily;const model=LotteryStats.drawModel(game,window.LotteryHistory?.[game]||[],daily?statsSessionEl.value:'all');statsResultsEl.replaceChildren();if(!model.draws.length){statsCoverageEl.textContent='No verified history available.';return;}statsCoverageEl.textContent=`${model.draws.length} verified ${GAMES[game].name} drawing${model.draws.length===1?'':'s'} from ${model.range.from} through ${model.range.to}.`;const top=model.main.slice(0,5).map(([n,c])=>`${n} (${c})`).join(', ');const bottom=[...model.main].sort((a,b)=>a[1]-b[1]||a[0]-b[0]).slice(0,5).map(([n,c])=>`${n} (${c})`).join(', ');const total=model.draws.flatMap(d=>d.main).length, odd=model.draws.flatMap(d=>d.main).filter(n=>n%2).length;statsResultsEl.append(statBox('Most frequent',top||'No values.'),statBox('Least frequent',bottom||'No values.'),statBox('Odd / even',`${odd} odd and ${total-odd} even values.`));if(model.specials.length)statsResultsEl.append(statBox('Special-number frequency',model.specials.slice(0,5).map(([n,c])=>`${n} (${c})`).join(', ')));}

document.querySelector('#generate').addEventListener('click',generateTickets);copyEl.addEventListener('click',async()=>{const config=GAMES[gameEl.value];const text=currentTickets.map((t,i)=>`${i+1}. ${t.playLabel}: ${t.main.join(' ')}${t.special===null?'':` | ${config.special.name}: ${t.special}`}`).join('\n');await navigator.clipboard.writeText(text);copyEl.textContent='Copied';setTimeout(()=>copyEl.textContent='Copy',1400);});
gameEl.addEventListener('change',updateGame);modeEl.addEventListener('change',()=>{updatePreferenceControls();resetTickets();});mainFavoritesEl.addEventListener('input',favoriteSummary);specialFavoritesEl.addEventListener('input',favoriteSummary);statsGameEl.addEventListener('change',renderStatistics);statsSessionEl.addEventListener('change',renderStatistics);window.addEventListener('lottery-history-loaded',()=>{document.querySelector('#stats-checked').textContent=window.LotteryHistory.checked;renderStatistics();});
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;}function updateInstallCard(){if(isStandalone()){installCard.hidden=true;return;}installCard.hidden=false;installButton.textContent=deferredInstall?'Install app':'How to install';installHelp.textContent=deferredInstall?'Lottery Hub is ready to install on this device.':'In Chrome, tap the three-dot menu, then choose Install app or Add to Home screen.';}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;updateInstallCard();});installButton.addEventListener('click',async()=>{if(!deferredInstall){installHelp.textContent='Tap the browser menu, then choose Add page to, Install app, or Add to Home screen.';return;}deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;updateInstallCard();});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
updateInstallCard();updateGame();renderStatistics();
